name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/ploomber/nbsnapshot@dev
          pip install -r requirements.txt
      - name: Test notebooks
        run: |
          nbsnapshot test example.ipynb --run
      - name: Update history
        run: |
          git add -f example.json
          git commit -m 'updates notebook history'
          git push

